import { Router } from 'express';
import * as controller from '../controllers/admin-brand.controller';
import { authenticate, authorize } from '../middlewares/auth.middleware';
const router = Router();
router.use(authenticate, authorize('admin'));
router.get('/', controller.listBrands);
router.post('/', controller.createBrand);
router.patch('/:brandId', controller.updateBrand);
router.delete('/:brandId', controller.deleteBrand);
export default router;
