import { useEffect, useMemo, useState } from "react";
import { useParams } from "react-router-dom";
import { adminApi, apiMessage, formatDate, formatVnd, type AdminCategory, type AdminProduct, type AdminVariant, type Paginated } from "../../lib/adminApi";
import { toast } from "../../store/toast.store";
import { Badge, Button, Card, ConfirmDialog, Field, Input, LoadingState, Modal, PageHeader, Select, Textarea } from "../../components/admin/ui";

type Tab = "vouchers" | "discounts" | "flash-sales" | "price-history";
type Voucher = { _id: string; code: string; name: string; type: string; value: number; minOrder: number; maxDiscount: number; startDate: string; endDate: string; usageLimit: number; usageLimitPerUser: number; usedCount: number; stackable: boolean; userSegment: string; isPrivate: boolean; isConcentratedPromotion: boolean; isActive: boolean };
type Discount = { _id: string; name: string; scope: "PRODUCT" | "CATEGORY"; type: "PERCENTAGE" | "FIXED"; value: number; maxDiscountAmount: number; products: { _id: string; name: string }[]; categories: { _id: string; name: string }[]; priority: number; startDate: string; endDate: string; isActive: boolean; isConcentratedPromotion: boolean; referencePriceConfirmed: boolean; referencePriceNote: string };
type FlashSale = { _id: string; name: string; variant: any; originalPrice: number; flashPrice: number; stockAllocated: number; soldCount: number; remaining: number; maxPerUser: number; startTime: string; endTime: string; status: string; isActive: boolean; isConcentratedPromotion: boolean; referencePriceConfirmed: boolean; referencePriceNote: string };
type History = { _id: string; variant: any; basePrice: number; validFrom: string; validTo: string | null; reason: string };

const tabs: Array<{ id: Tab; label: string }> = [{ id: "vouchers", label: "Voucher" }, { id: "discounts", label: "Discount sản phẩm" }, { id: "flash-sales", label: "Flash Sale" }, { id: "price-history", label: "Lịch sử giá" }];
const localDateTime = (value?: string | Date) => { const date = value ? new Date(value) : new Date(); const shifted = new Date(date.getTime() - date.getTimezoneOffset() * 60000); return shifted.toISOString().slice(0, 16); };
const future = (days: number) => { const date = new Date(); date.setDate(date.getDate() + days); return localDateTime(date); };
const ids = (values: any[] = []) => values.map((item) => String(item?._id || item));

const emptyVoucher = () => ({ code: "", name: "", type: "percentage", value: "10", minOrderValue: "0", maxDiscountAmount: "0", startDate: localDateTime(), endDate: future(30), usageLimit: "0", usageLimitPerUser: "1", stackable: true, userSegment: "ALL", isPrivate: false, isActive: true });
const emptyDiscount = () => ({ name: "", scope: "PRODUCT" as const, type: "PERCENTAGE" as const, value: "10", maxDiscountAmount: "0", products: [] as string[], categories: [] as string[], priority: "0", startDate: localDateTime(), endDate: future(30), isActive: true, isConcentratedPromotion: false, referencePriceConfirmed: false, referencePriceNote: "" });
const emptyFlash = () => ({ name: "", variant: "", flashPrice: "", stockAllocated: "1", maxPerUser: "1", startTime: localDateTime(), endTime: future(1), isActive: true, isConcentratedPromotion: false, referencePriceConfirmed: false, referencePriceNote: "" });

function MultiSelect({ value, options, onChange }: { value: string[]; options: { id: string; name: string }[]; onChange: (value: string[]) => void }) {
  return <Select multiple className="h-36" value={value} onChange={(event) => onChange(Array.from(event.target.selectedOptions, (option) => option.value))}>{options.map((option) => <option key={option.id} value={option.id}>{option.name}</option>)}</Select>;
}

function EvidenceFields({ form, set }: { form: any; set: (patch: any) => void }) {
  return <div className="space-y-3 border-t border-gray-100 pt-4"><label className="flex items-start gap-2 text-sm"><input type="checkbox" checked={form.isConcentratedPromotion} onChange={(e) => set({ isConcentratedPromotion: e.target.checked })} /><span>Chương trình khuyến mại tập trung được phép vượt hạn mức thông thường</span></label><label className="flex items-start gap-2 text-sm"><input type="checkbox" checked={form.referencePriceConfirmed} onChange={(e) => set({ referencePriceConfirmed: e.target.checked })} /><span>Có chứng từ giá đã bán thực tế ngoài hệ thống</span></label>{form.referencePriceConfirmed && <Field label="Ghi chú chứng cứ" hint="Ví dụ: số hóa đơn, thời gian bán, nguồn dữ liệu đối chiếu"><Textarea rows={3} value={form.referencePriceNote} onChange={(e) => set({ referencePriceNote: e.target.value })} /></Field>}</div>;
}

export default function AdminPromotions() {
  const { tab: routeTab } = useParams();
  const tab = tabs.some((item) => item.id === routeTab) ? routeTab as Tab : "vouchers";
  const [loading, setLoading] = useState(true);
  const [vouchers, setVouchers] = useState<Voucher[]>([]); const [discounts, setDiscounts] = useState<Discount[]>([]); const [flashSales, setFlashSales] = useState<FlashSale[]>([]); const [history, setHistory] = useState<History[]>([]);
  const [products, setProducts] = useState<AdminProduct[]>([]); const [categories, setCategories] = useState<AdminCategory[]>([]); const [variants, setVariants] = useState<AdminVariant[]>([]);
  const [modal, setModal] = useState(false); const [editing, setEditing] = useState<any>(null); const [saving, setSaving] = useState(false); const [deleting, setDeleting] = useState<any>(null);
  const [voucherForm, setVoucherForm] = useState(emptyVoucher()); const [discountForm, setDiscountForm] = useState(emptyDiscount()); const [flashForm, setFlashForm] = useState(emptyFlash()); const [historyVariant, setHistoryVariant] = useState("");

  async function allProducts() { const first = await adminApi.get<Paginated<AdminProduct>>("/products", { page: 1, limit: 100 }); const rest = await Promise.all(Array.from({ length: Math.max(0, first.totalPages - 1) }, (_, index) => adminApi.get<Paginated<AdminProduct>>("/products", { page: index + 2, limit: 100 }))); return [first, ...rest].flatMap((page) => page.data); }
  async function load() { try { setLoading(true); const [v, d, f, h, p, c, vr] = await Promise.all([adminApi.get<Voucher[]>("/promotions/vouchers"), adminApi.get<Discount[]>("/promotions/discounts"), adminApi.get<FlashSale[]>("/promotions/flash-sales"), adminApi.get<History[]>("/promotions/price-history", { variant: historyVariant || undefined }), allProducts(), adminApi.get<AdminCategory[]>("/categories"), adminApi.get<AdminVariant[]>("/variants")]); setVouchers(v); setDiscounts(d); setFlashSales(f); setHistory(h); setProducts(p); setCategories(c); setVariants(vr); } catch (error) { toast.error(apiMessage(error, "Không tải được chương trình ưu đãi")); } finally { setLoading(false); } }
  useEffect(() => { load(); /* eslint-disable-next-line react-hooks/exhaustive-deps */ }, [historyVariant]);

  const productOptions = products.map((item) => ({ id: item.id, name: item.name }));
  const categoryOptions = categories.map((item) => ({ id: item.id, name: item.name }));
  const variantName = (item: AdminVariant) => `${item.product?.name || "Sản phẩm"} · ${item.volume || item.sku} · ${formatVnd(item.price)}`;

  function openCreate() { setEditing(null); if (tab === "vouchers") setVoucherForm(emptyVoucher()); if (tab === "discounts") setDiscountForm(emptyDiscount()); if (tab === "flash-sales") setFlashForm(emptyFlash()); setModal(true); }
  function openEdit(item: any) { setEditing(item); if (tab === "vouchers") setVoucherForm({ code: item.code, name: item.name || "", type: item.type === "percent" ? "percentage" : item.type, value: String(item.value || 0), minOrderValue: String(item.minOrder || 0), maxDiscountAmount: String(item.maxDiscount || 0), startDate: localDateTime(item.startDate || item.createdAt), endDate: localDateTime(item.endDate || item.expiresAt), usageLimit: String(item.usageLimit || 0), usageLimitPerUser: String(item.usageLimitPerUser || 0), stackable: item.stackable !== false, userSegment: item.userSegment || "ALL", isPrivate: Boolean(item.isPrivate), isActive: item.isActive !== false }); if (tab === "discounts") setDiscountForm({ name: item.name, scope: item.scope, type: item.type, value: String(item.value), maxDiscountAmount: String(item.maxDiscountAmount || 0), products: ids(item.products), categories: ids(item.categories), priority: String(item.priority || 0), startDate: localDateTime(item.startDate), endDate: localDateTime(item.endDate), isActive: item.isActive !== false, isConcentratedPromotion: Boolean(item.isConcentratedPromotion), referencePriceConfirmed: Boolean(item.referencePriceConfirmed), referencePriceNote: item.referencePriceNote || "" }); if (tab === "flash-sales") setFlashForm({ name: item.name, variant: String(item.variant?._id || item.variant), flashPrice: String(item.flashPrice), stockAllocated: String(item.stockAllocated), maxPerUser: String(item.maxPerUser || 0), startTime: localDateTime(item.startTime), endTime: localDateTime(item.endTime), isActive: item.isActive !== false, isConcentratedPromotion: Boolean(item.isConcentratedPromotion), referencePriceConfirmed: Boolean(item.referencePriceConfirmed), referencePriceNote: item.referencePriceNote || "" }); setModal(true); }

  async function save() { try { setSaving(true); const section = tab === "vouchers" ? "vouchers" : tab === "discounts" ? "discounts" : "flash-sales"; const raw: any = tab === "vouchers" ? voucherForm : tab === "discounts" ? discountForm : flashForm; const payload: any = { ...raw }; for (const key of ["value", "minOrderValue", "maxDiscountAmount", "usageLimit", "usageLimitPerUser", "priority", "flashPrice", "stockAllocated", "maxPerUser"]) if (key in payload) payload[key] = Number(payload[key] || 0); if (editing) await adminApi.put(`/promotions/${section}/${editing._id}`, payload); else await adminApi.post(`/promotions/${section}`, payload); toast.success(editing ? "Đã cập nhật ưu đãi" : "Đã tạo ưu đãi"); setModal(false); await load(); } catch (error) { toast.error(apiMessage(error, "Không lưu được ưu đãi")); } finally { setSaving(false); } }
  async function remove() { if (!deleting) return; try { const section = tab === "vouchers" ? "vouchers" : tab === "discounts" ? "discounts" : "flash-sales"; await adminApi.del(`/promotions/${section}/${deleting._id}`); toast.success("Đã xóa ưu đãi"); setDeleting(null); await load(); } catch (error) { toast.error(apiMessage(error, "Không xóa được ưu đãi")); } }

  return <div><PageHeader title="Ưu đãi & Voucher" subtitle="Giá niêm yết không bị ghi đè; mọi ưu đãi được resolve và snapshot khi đặt hàng" actions={tab !== "price-history" ? <Button onClick={openCreate}>+ Tạo mới</Button> : undefined} />
    <div className="mb-5 flex gap-1 overflow-x-auto border-b">{tabs.map((item) => <a key={item.id} href={`/admin/promotions/${item.id}`} className={`shrink-0 border-b-2 px-4 py-3 text-sm ${tab === item.id ? "border-black text-black" : "border-transparent text-gray-500"}`}>{item.label}</a>)}</div>
    {loading ? <LoadingState /> : <Card className="overflow-hidden rounded-md shadow-none"><div className="overflow-x-auto">
      {tab === "vouchers" && <table className="w-full min-w-[900px] text-sm"><thead><tr className="border-b text-left text-xs uppercase text-gray-400"><th className="p-4">Mã</th><th>Tên</th><th>Ưu đãi</th><th>Điều kiện</th><th>Lượt dùng</th><th>Thời gian</th><th>Trạng thái</th><th /></tr></thead><tbody>{vouchers.map((item) => <tr key={item._id} className="border-b"><td className="p-4 font-mono font-semibold">{item.code}</td><td>{item.name || "—"}{item.isPrivate && <p className="text-xs text-gray-400">Riêng tư</p>}</td><td>{item.type === "free_shipping" ? "Miễn phí ship" : item.type === "fixed" ? formatVnd(item.value) : `${item.value}%`}</td><td>Từ {formatVnd(item.minOrder)}<p className="text-xs text-gray-400">{item.stackable ? "Dùng chung ưu đãi" : "Không cộng dồn"} · {item.userSegment}</p></td><td>{item.usedCount || 0}/{item.usageLimit || "∞"}<p className="text-xs text-gray-400">Mỗi khách {item.usageLimitPerUser || "∞"}</p></td><td>{formatDate(item.startDate)}<br />{formatDate(item.endDate)}</td><td><Badge color={item.isActive ? "green" : "gray"}>{item.isActive ? "Đang bật" : "Đã tắt"}</Badge></td><td><div className="flex gap-2"><Button variant="secondary" onClick={() => openEdit(item)}>Sửa</Button><Button variant="danger" onClick={() => setDeleting(item)}>Xóa</Button></div></td></tr>)}</tbody></table>}
      {tab === "discounts" && <table className="w-full min-w-[900px] text-sm"><thead><tr className="border-b text-left text-xs uppercase text-gray-400"><th className="p-4">Chương trình</th><th>Phạm vi</th><th>Mức giảm</th><th>Priority</th><th>Thời gian</th><th>Trạng thái</th><th /></tr></thead><tbody>{discounts.map((item) => <tr key={item._id} className="border-b"><td className="p-4 font-medium">{item.name}</td><td>{item.scope === "PRODUCT" ? `${item.products?.length || 0} sản phẩm` : `${item.categories?.length || 0} danh mục`}</td><td>{item.type === "PERCENTAGE" ? `${item.value}%` : formatVnd(item.value)}</td><td>{item.priority}</td><td>{formatDate(item.startDate)}<br />{formatDate(item.endDate)}</td><td><Badge color={item.isActive ? "green" : "gray"}>{item.isActive ? "Đang bật" : "Đã tắt"}</Badge></td><td><div className="flex gap-2"><Button variant="secondary" onClick={() => openEdit(item)}>Sửa</Button><Button variant="danger" onClick={() => setDeleting(item)}>Xóa</Button></div></td></tr>)}</tbody></table>}
      {tab === "flash-sales" && <table className="w-full min-w-[960px] text-sm"><thead><tr className="border-b text-left text-xs uppercase text-gray-400"><th className="p-4">Flash sale</th><th>Sản phẩm</th><th>Giá gốc / Flash</th><th>Phân bổ</th><th>Mỗi khách</th><th>Thời gian</th><th>Trạng thái</th><th /></tr></thead><tbody>{flashSales.map((item) => <tr key={item._id} className="border-b"><td className="p-4 font-medium">{item.name}</td><td>{item.variant?.product?.name || "—"}<p className="text-xs text-gray-400">{item.variant?.volume || item.variant?.sku}</p></td><td><span className="text-gray-400 line-through">{formatVnd(item.originalPrice)}</span><br /><strong className="text-red-700">{formatVnd(item.flashPrice)}</strong></td><td>{item.soldCount}/{item.stockAllocated}<p className="text-xs text-gray-400">Còn {item.remaining}</p></td><td>{item.maxPerUser || "∞"}</td><td>{formatDate(item.startTime)}<br />{formatDate(item.endTime)}</td><td><Badge color={item.status === "ACTIVE" ? "green" : item.status === "UPCOMING" ? "blue" : "gray"}>{item.status}</Badge></td><td><div className="flex gap-2"><Button variant="secondary" onClick={() => openEdit(item)}>Sửa</Button><Button variant="danger" onClick={() => setDeleting(item)}>Xóa</Button></div></td></tr>)}</tbody></table>}
      {tab === "price-history" && <div><div className="border-b p-4"><Select className="max-w-md" value={historyVariant} onChange={(e) => setHistoryVariant(e.target.value)}><option value="">Tất cả biến thể</option>{variants.map((item) => <option key={item.id} value={item.id}>{variantName(item)}</option>)}</Select></div><table className="w-full min-w-[720px] text-sm"><thead><tr className="border-b text-left text-xs uppercase text-gray-400"><th className="p-4">Sản phẩm</th><th>Giá niêm yết</th><th>Hiệu lực từ</th><th>Hiệu lực đến</th><th>Lý do</th></tr></thead><tbody>{history.map((item) => <tr key={item._id} className="border-b"><td className="p-4">{item.variant?.product?.name || "—"}<p className="text-xs text-gray-400">{item.variant?.volume || item.variant?.sku}</p></td><td>{formatVnd(item.basePrice)}</td><td>{formatDate(item.validFrom)}</td><td>{item.validTo ? formatDate(item.validTo) : <Badge color="green">Hiện tại</Badge>}</td><td>{item.reason || "—"}</td></tr>)}</tbody></table></div>}
    </div></Card>}

    <Modal open={modal} onClose={() => setModal(false)} wide title={editing ? "Chỉnh sửa ưu đãi" : "Tạo ưu đãi"} footer={<><Button variant="secondary" onClick={() => setModal(false)}>Hủy</Button><Button onClick={save} disabled={saving}>{saving ? "Đang lưu..." : "Lưu"}</Button></>}>
      {tab === "vouchers" && <div className="grid gap-4 sm:grid-cols-2"><Field label="Mã voucher"><Input value={voucherForm.code} onChange={(e) => setVoucherForm({ ...voucherForm, code: e.target.value.toUpperCase() })} /></Field><Field label="Tên chương trình"><Input value={voucherForm.name} onChange={(e) => setVoucherForm({ ...voucherForm, name: e.target.value })} /></Field><Field label="Loại"><Select value={voucherForm.type} onChange={(e) => setVoucherForm({ ...voucherForm, type: e.target.value })}><option value="percentage">Phần trăm</option><option value="fixed">Số tiền cố định</option><option value="free_shipping">Miễn phí vận chuyển</option></Select></Field><Field label="Giá trị"><Input type="number" disabled={voucherForm.type === "free_shipping"} value={voucherForm.value} onChange={(e) => setVoucherForm({ ...voucherForm, value: e.target.value })} /></Field><Field label="Đơn tối thiểu"><Input type="number" value={voucherForm.minOrderValue} onChange={(e) => setVoucherForm({ ...voucherForm, minOrderValue: e.target.value })} /></Field><Field label="Giảm tối đa"><Input type="number" value={voucherForm.maxDiscountAmount} onChange={(e) => setVoucherForm({ ...voucherForm, maxDiscountAmount: e.target.value })} /></Field><Field label="Bắt đầu"><Input type="datetime-local" value={voucherForm.startDate} onChange={(e) => setVoucherForm({ ...voucherForm, startDate: e.target.value })} /></Field><Field label="Kết thúc"><Input type="datetime-local" value={voucherForm.endDate} onChange={(e) => setVoucherForm({ ...voucherForm, endDate: e.target.value })} /></Field><Field label="Giới hạn toàn hệ thống"><Input type="number" value={voucherForm.usageLimit} onChange={(e) => setVoucherForm({ ...voucherForm, usageLimit: e.target.value })} /></Field><Field label="Giới hạn mỗi khách"><Input type="number" value={voucherForm.usageLimitPerUser} onChange={(e) => setVoucherForm({ ...voucherForm, usageLimitPerUser: e.target.value })} /></Field><Field label="Phân khúc khách"><Select value={voucherForm.userSegment} onChange={(e) => setVoucherForm({ ...voucherForm, userSegment: e.target.value })}>{["ALL", "NEW", "RETURNING", "LOYAL", "VIP"].map((item) => <option key={item}>{item}</option>)}</Select></Field><div className="space-y-2 pt-6"><label className="flex gap-2 text-sm"><input type="checkbox" checked={voucherForm.stackable} onChange={(e) => setVoucherForm({ ...voucherForm, stackable: e.target.checked })} />Cho dùng chung ưu đãi sản phẩm</label><label className="flex gap-2 text-sm"><input type="checkbox" checked={voucherForm.isPrivate} onChange={(e) => setVoucherForm({ ...voucherForm, isPrivate: e.target.checked })} />Voucher riêng tư</label><label className="flex gap-2 text-sm"><input type="checkbox" checked={voucherForm.isActive} onChange={(e) => setVoucherForm({ ...voucherForm, isActive: e.target.checked })} />Kích hoạt</label></div></div>}
      {tab === "discounts" && <div className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><Field label="Tên chương trình"><Input value={discountForm.name} onChange={(e) => setDiscountForm({ ...discountForm, name: e.target.value })} /></Field><Field label="Priority"><Input type="number" value={discountForm.priority} onChange={(e) => setDiscountForm({ ...discountForm, priority: e.target.value })} /></Field><Field label="Phạm vi"><Select value={discountForm.scope} onChange={(e) => setDiscountForm({ ...discountForm, scope: e.target.value as any, products: [], categories: [] })}><option value="PRODUCT">Sản phẩm</option><option value="CATEGORY">Danh mục</option></Select></Field><Field label="Loại giảm"><Select value={discountForm.type} onChange={(e) => setDiscountForm({ ...discountForm, type: e.target.value as any })}><option value="PERCENTAGE">Phần trăm</option><option value="FIXED">Số tiền cố định</option></Select></Field><Field label="Giá trị"><Input type="number" value={discountForm.value} onChange={(e) => setDiscountForm({ ...discountForm, value: e.target.value })} /></Field><Field label="Giảm tối đa"><Input type="number" value={discountForm.maxDiscountAmount} onChange={(e) => setDiscountForm({ ...discountForm, maxDiscountAmount: e.target.value })} /></Field><Field label="Bắt đầu"><Input type="datetime-local" value={discountForm.startDate} onChange={(e) => setDiscountForm({ ...discountForm, startDate: e.target.value })} /></Field><Field label="Kết thúc"><Input type="datetime-local" value={discountForm.endDate} onChange={(e) => setDiscountForm({ ...discountForm, endDate: e.target.value })} /></Field></div><Field label={discountForm.scope === "PRODUCT" ? "Sản phẩm áp dụng (Ctrl để chọn nhiều)" : "Danh mục áp dụng (Ctrl để chọn nhiều)"}>{discountForm.scope === "PRODUCT" ? <MultiSelect value={discountForm.products} options={productOptions} onChange={(value) => setDiscountForm({ ...discountForm, products: value })} /> : <MultiSelect value={discountForm.categories} options={categoryOptions} onChange={(value) => setDiscountForm({ ...discountForm, categories: value })} />}</Field><label className="flex gap-2 text-sm"><input type="checkbox" checked={discountForm.isActive} onChange={(e) => setDiscountForm({ ...discountForm, isActive: e.target.checked })} />Kích hoạt</label><EvidenceFields form={discountForm} set={(patch) => setDiscountForm({ ...discountForm, ...patch })} /></div>}
      {tab === "flash-sales" && <div className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><Field label="Tên Flash Sale"><Input value={flashForm.name} onChange={(e) => setFlashForm({ ...flashForm, name: e.target.value })} /></Field><Field label="Biến thể"><Select value={flashForm.variant} onChange={(e) => setFlashForm({ ...flashForm, variant: e.target.value })}><option value="">Chọn biến thể</option>{variants.map((item) => <option key={item.id} value={item.id}>{variantName(item)}</option>)}</Select></Field><Field label="Giá Flash Sale"><Input type="number" value={flashForm.flashPrice} onChange={(e) => setFlashForm({ ...flashForm, flashPrice: e.target.value })} /></Field><Field label="Tồn phân bổ"><Input type="number" value={flashForm.stockAllocated} onChange={(e) => setFlashForm({ ...flashForm, stockAllocated: e.target.value })} /></Field><Field label="Tối đa mỗi khách"><Input type="number" value={flashForm.maxPerUser} onChange={(e) => setFlashForm({ ...flashForm, maxPerUser: e.target.value })} /></Field><Field label="Bắt đầu"><Input type="datetime-local" value={flashForm.startTime} onChange={(e) => setFlashForm({ ...flashForm, startTime: e.target.value })} /></Field><Field label="Kết thúc"><Input type="datetime-local" value={flashForm.endTime} onChange={(e) => setFlashForm({ ...flashForm, endTime: e.target.value })} /></Field></div><label className="flex gap-2 text-sm"><input type="checkbox" checked={flashForm.isActive} onChange={(e) => setFlashForm({ ...flashForm, isActive: e.target.checked })} />Kích hoạt</label><EvidenceFields form={flashForm} set={(patch) => setFlashForm({ ...flashForm, ...patch })} /></div>}
    </Modal>
    <ConfirmDialog open={!!deleting} title="Xóa ưu đãi" message="Đơn hàng cũ vẫn giữ snapshot giá và ưu đãi. Bạn có chắc muốn xóa?" onCancel={() => setDeleting(null)} onConfirm={remove} />
  </div>;
}
